### ISSUE TITLE
Add (Pew) self ref 

### ISSUE THREAD

**Issue by amrrs** [ThinkR-open/companies-using-r#15]
https://medium.com/pew-research-center-decoded/using-tidyverse-tools-with-pew-research-center-survey-data-in-r-bdfe61de0909

**Comment by statnmap** [comment]
Thank you for your proposition.  
However, in this list, we want to show that R is used in production in Companies, Officials and NGOs. Indeed, R is sometimes seen as a language only used by researchers for some small analyses. With this repository, we want to show that this is not the only place where R is used, and that we can trust it for production environments.  
Hence, I am sure that Pew Research Center is doing great job using R for research, but I am not sure that it enters the scope of what we want to show with this list.  
But maybe, I misunderstood its presentation. Feel free to reopen this issue if you think so.
